-- MySQL Script generated by MySQL Workbench
-- Sat Jan 17 16:14:53 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema flytau
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema flytau
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `flytau` DEFAULT CHARACTER SET utf8mb4 ;
USE `flytau` ;

-- -----------------------------------------------------
-- Table `flytau`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flytau`.`admin` (
  `ID` INT NOT NULL,
  `fname` VARCHAR(255) NOT NULL,
  `lname` VARCHAR(255) NOT NULL,
  `start_date` DATE NULL DEFAULT NULL,
  `city` VARCHAR(255) NULL DEFAULT NULL,
  `street` VARCHAR(255) NULL DEFAULT NULL,
  `house_number` INT NULL DEFAULT NULL,
  `phone` VARCHAR(50) NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `flytau`.`registered_customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flytau`.`registered_customers` (
  `email` VARCHAR(255) NOT NULL,
  `fname` VARCHAR(255) NOT NULL,
  `lname` VARCHAR(255) NOT NULL,
  `date_of_birth` DATE NULL DEFAULT NULL,
  `passport` VARCHAR(50) NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `registration_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `flytau`.`unregistered_customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flytau`.`unregistered_customers` (
  `email` VARCHAR(255) NOT NULL,
  `fname` VARCHAR(255) NOT NULL,
  `lname` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `flytau`.`bookings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flytau`.`bookings` (
  `booking_code` INT NOT NULL,
  `status` VARCHAR(50) NOT NULL,
  `total_price` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `booking_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `registered_email` VARCHAR(255) NULL DEFAULT NULL,
  `unregistered_email` VARCHAR(255) NULL DEFAULT NULL,
  `registered_customers_email` VARCHAR(255) NOT NULL,
  `unregistered_customers_email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`booking_code`),
  INDEX `fk_bookings_registered_customers1_idx` (`registered_customers_email` ASC) VISIBLE,
  INDEX `fk_bookings_unregistered_customers1_idx` (`unregistered_customers_email` ASC) VISIBLE,
  CONSTRAINT `fk_bookings_registered_customers1`
    FOREIGN KEY (`registered_customers_email`)
    REFERENCES `flytau`.`registered_customers` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bookings_unregistered_customers1`
    FOREIGN KEY (`unregistered_customers_email`)
    REFERENCES `flytau`.`unregistered_customers` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `flytau`.`plane`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flytau`.`plane` (
  `ID` INT NOT NULL,
  `Manufacturer` VARCHAR(255) NOT NULL,
  `Size` VARCHAR(255) NULL DEFAULT NULL,
  `Purchase_Date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `flytau`.`classes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flytau`.`classes` (
  `Plane_ID` INT NOT NULL,
  `Class_Type` VARCHAR(255) NOT NULL,
  `Number_of_Rows` INT NOT NULL,
  `Number_of_Columns` INT NOT NULL,
  PRIMARY KEY (`Plane_ID`, `Class_Type`),
  CONSTRAINT `fk_Classes_Plane`
    FOREIGN KEY (`Plane_ID`)
    REFERENCES `flytau`.`plane` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `flytau`.`flight_attendant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flytau`.`flight_attendant` (
  `ID` INT NOT NULL,
  `fname` VARCHAR(255) NOT NULL,
  `lname` VARCHAR(255) NOT NULL,
  `start_date` DATE NULL DEFAULT NULL,
  `city` VARCHAR(255) NULL DEFAULT NULL,
  `street` VARCHAR(255) NULL DEFAULT NULL,
  `house_number` INT NULL DEFAULT NULL,
  `phone` VARCHAR(50) NULL DEFAULT NULL,
  `training` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `flytau`.`flight_duration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flytau`.`flight_duration` (
  `Departure_Airport` CHAR(3) NOT NULL,
  `Destination_Airport` CHAR(3) NOT NULL,
  `Duration_in_Hours` FLOAT NOT NULL,
  PRIMARY KEY (`Departure_Airport`, `Destination_Airport`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `flytau`.`flights`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flytau`.`flights` (
  `Flight_Date` DATE NOT NULL,
  `Departure_Time` TIME NOT NULL,
  `Plane_ID` INT NOT NULL,
  `Landing_Time` TIME NULL DEFAULT NULL,
  `Departure_Airport` CHAR(3) NOT NULL,
  `Destination_Airport` CHAR(3) NOT NULL,
  `status` VARCHAR(50) NOT NULL,
  `economy_price` DECIMAL(10,2) NOT NULL,
  `business_price` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`Flight_Date`, `Departure_Time`, `Plane_ID`),
  UNIQUE INDEX `uq_Flights_DateTime` (`Flight_Date` ASC, `Departure_Time` ASC) VISIBLE,
  INDEX `fk_Flights_Plane` (`Plane_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Flights_Plane`
    FOREIGN KEY (`Plane_ID`)
    REFERENCES `flytau`.`plane` (`ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `flytau`.`phone_numbers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flytau`.`phone_numbers` (
  `email` VARCHAR(255) NOT NULL,
  `phone_number` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`email`, `phone_number`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `flytau`.`pilot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flytau`.`pilot` (
  `ID` INT NOT NULL,
  `fname` VARCHAR(255) NOT NULL,
  `lname` VARCHAR(255) NOT NULL,
  `start_date` DATE NULL DEFAULT NULL,
  `city` VARCHAR(255) NULL DEFAULT NULL,
  `street` VARCHAR(255) NULL DEFAULT NULL,
  `house_number` INT NULL DEFAULT NULL,
  `phone` VARCHAR(50) NULL DEFAULT NULL,
  `training` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `flytau`.`staff_on_flight`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flytau`.`staff_on_flight` (
  `flight_date` DATE NOT NULL,
  `departure_time` TIME NOT NULL,
  `plane_ID` INT NOT NULL,
  `ID` INT NOT NULL,
  `pilot_ID` INT NOT NULL,
  `flight_attendant_ID` INT NOT NULL,
  PRIMARY KEY (`flight_date`, `departure_time`, `plane_ID`, `ID`),
  INDEX `fk_staff_on_flight_pilot1_idx` (`pilot_ID` ASC) VISIBLE,
  INDEX `fk_staff_on_flight_flight_attendant1_idx` (`flight_attendant_ID` ASC) VISIBLE,
  CONSTRAINT `fk_StaffOnFlight_Flights`
    FOREIGN KEY (`flight_date` , `departure_time` , `plane_ID`)
    REFERENCES `flytau`.`flights` (`Flight_Date` , `Departure_Time` , `Plane_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_staff_on_flight_pilot1`
    FOREIGN KEY (`pilot_ID`)
    REFERENCES `flytau`.`pilot` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_staff_on_flight_flight_attendant1`
    FOREIGN KEY (`flight_attendant_ID`)
    REFERENCES `flytau`.`flight_attendant` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `flytau`.`tickets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flytau`.`tickets` (
  `row` INT NOT NULL,
  `col` INT NOT NULL,
  `booking_code` INT NOT NULL,
  `flight_date` DATE NOT NULL,
  `departure_time` TIME NOT NULL,
  PRIMARY KEY (`booking_code`, `flight_date`, `departure_time`, `row`, `col`),
  INDEX `fk_Tickets_Flights` (`flight_date` ASC, `departure_time` ASC) VISIBLE,
  CONSTRAINT `fk_Tickets_Bookings`
    FOREIGN KEY (`booking_code`)
    REFERENCES `flytau`.`bookings` (`booking_code`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Tickets_Flights`
    FOREIGN KEY (`flight_date` , `departure_time`)
    REFERENCES `flytau`.`flights` (`Flight_Date` , `Departure_Time`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
